name: "demowebsite1"
address: "https://kubernetes.default.svc"
app_namespace: "demo"
helmchart_url: "registry-1.docker.io/bitnamicharts"
chart: "nginx"
version: "15.14.0"
repoversion: ""
update_strategy: latest
app_values: |-
        service:
          type: "LoadBalancer"
          ports:
            http: 8888
        staticSiteConfigmap: "index-html-configmap"
        cloneStaticSiteFromGit.repository:
        serverBlock: |-
          server {
            listen 8888;
            root /app/;
            index index.html index.htm;
            location /demovol1/ {
              alias /demovol1/;
              index __i;
              autoindex on;
              autoindex_format json;
              disable_symlinks off;
            }
            location / {
              root /app/;
            }
          }
        extraDeploy:
          - |
            apiVersion: v1
            kind: ConfigMap
            metadata:
                name: index-html-configmap
                namespace: demo
            data:
                index.html: |
                    <html>
                    <h1>Welcome</h1>
                    </br>
                    <h1> Demo website 1 deployed! </h1>
                    </html>
          - |
            apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: demovol1
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 4Gi
        extraVolumes:
          - name: demovol1
            persistentVolumeClaim:
              claimName: demovol1
        extraVolumeMounts:
          - mountPath: /demovol1
            name: demovol1
